# Модуль NumPy

NumPy - библиотека с открытым исходным кодом для языка программирования Python. 

Возможности: поддержка многомерных массивов; поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами. [Википедия](https://ru.wikipedia.org/wiki/NumPy)

https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

In [1]:
import numpy as np # Негласно принятое сокращение

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

## ndarray

Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.

```
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)
```

`shape` - размерность массива, кортеж натуральных чисел, показывающий длину массива по каждой оси.

In [4]:
Data = np.ndarray((4,),dtype = int)
Data, Data.shape

(array([0, 0, 0, 0]), (4,))

`dtype` -  тип элементов, можно использовать встроенные, или типы из numpy:

` bool_, character, int_, int8, int16, int32, int64, float16, float32, float64, complex64, object_.`

In [5]:
# Двумерный массив - матрица
A = np.ndarray((3,4), dtype = np.float16)

In [6]:
A[1,1]=111

In [7]:
print(A)# Заполняется мусором из памяти

[[  0.   0.   0.   0.]
 [  0. 111.   0.   0.]
 [  0.   0.   0.   0.]]


## Создание массивов

### Массив из нулей, единиц, единичная матрица

In [8]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((5,), dtype=np.float16)

array([1., 1., 1., 1., 1.], dtype=float16)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(3,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [12]:
type(np.eye(3))

numpy.ndarray

In [13]:
np.empty((3, 5)) #?????

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Другие способы создания

`numpy.array()` - функция, создающая объект типа `ndarray`:

In [14]:
a = np.array([[1,2,3],[5,6,7]])
a, type(a)

(array([[1, 2, 3],
        [5, 6, 7]]), numpy.ndarray)

In [15]:
b =  np.array([[x*x for x in range(10)],[1]*10,[3]*10])
b

array([[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3]])

### Функции arange, linspace, fromfunction

In [16]:
print(np.arange(10), 
      np.arange(0, 1, 0.1),
      np.array([np.arange(10), np.arange(0, 1, 0.1)]),sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0.  1.  2.  3.  4.  5.  6.  7.  8.  9. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]]


In [17]:
# В отличии от arange можно точно указать количество элементов
np.linspace(0, 1, 5)  # 5 чисел от 0 до 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# def fun(i,j):
#     return (i + j) % 2 == 0

np.fromfunction(lambda i,j: (i + j) % 2 == 0, (3, 3), dtype=int)

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

**Пример**. Создание массива пользовательского типа,в виде сетки точек на плоскости с координатами из отрезка $[0, 1]$.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html

In [19]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z, np.dtype(Z[1,1]))

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]] [('x', '<f8'), ('y', '<f8')]


## Изменение формы массива:

In [20]:
a = np.arange(1,10)
a.shape

(9,)

In [21]:
a.reshape(3,3)  #  [:,1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a, a.shape

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), (9,))

In [23]:
a.shape = (3,3)

In [24]:
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), (3, 3))

## Срезы ndarray

Для одномерных массивов аналогично спискам:

In [25]:
a = np.arange(1,10)
a[:4], a[4:]

(array([1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

Многомерные масивы:

In [26]:
# Матрица из случайных чисел от 0 до 4 включительно размера 3 на 4
data = np.random.randint(0, 5, (3, 4))
data

array([[2, 4, 2, 1],
       [3, 2, 1, 1],
       [2, 3, 2, 4]])

In [27]:
data[2], data[2,:], data[2, 0:4]

(array([2, 3, 2, 4]), array([2, 3, 2, 4]), array([2, 3, 2, 4]))

In [28]:
data[:,1:] # без первого столбца

array([[4, 2, 1],
       [2, 1, 1],
       [3, 2, 4]])

Срез как представление данных, позволяет изменить часть массива:

In [29]:
data[:,3] = 99
data

array([[ 2,  4,  2, 99],
       [ 3,  2,  1, 99],
       [ 2,  3,  2, 99]])

## Операции с массивами

Арифметические операции:

In [30]:
a = np.array([2]*4)
b = np.arange(4)
print(a,b)

[2 2 2 2] [0 1 2 3]


In [31]:
print(
a + b,
a - b,
a * b,
a / b,
a % b,
a ** b,
sep='\n')

[2 3 4 5]
[ 2  1  0 -1]
[0 2 4 6]
[       inf 2.         1.         0.66666667]
[0 0 0 2]
[1 2 4 8]


C:\Users\Artem\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
C:\Users\Artem\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in remainder
  


In [32]:
b * 2

array([0, 2, 4, 6])

In [33]:
b + 3

array([3, 4, 5, 6])

In [34]:
b**2

array([0, 1, 4, 9], dtype=int32)

### Математические функции NumPy:

https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [35]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [36]:
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [37]:
np.sum(b)

6

In [38]:
np.array([3,2,5]).T

array([3, 2, 5])

In [39]:
data

array([[ 2,  4,  2, 99],
       [ 3,  2,  1, 99],
       [ 2,  3,  2, 99]])

In [40]:
np.sum(data), np.sum(data, axis=0), np.sum(data, axis=1)

(318, array([  7,   9,   5, 297]), array([107, 105, 106]))

**Многие операции реализованы методами ndarray:**

In [41]:
data.sum(axis=0)

array([  7,   9,   5, 297])

In [42]:
data.max(axis=0)

array([ 3,  4,  2, 99])

In [45]:
#dir(data)

### Фильтрация данных
**Операции сравнения** позволяют создавать фильтры:

In [46]:
b

array([0, 1, 2, 3])

In [47]:
b>1

array([False, False,  True,  True])

In [48]:
b % 2 == 0

array([ True, False,  True, False])

In [49]:
b[b > 1]

array([2, 3])

In [50]:
b[b % 2 == 0]

array([0, 2])

In [51]:
# Можно изменить отфильтрованную часть
b[b > 1] = 5
b

array([0, 1, 5, 5])

### Матричные операции

In [52]:
a = np.array([[1,2],[3,4],[2,1]])
b = np.array([[3,-2],[2,1]])
print(a,b, sep='\n')

[[1 2]
 [3 4]
 [2 1]]
[[ 3 -2]
 [ 2  1]]


In [53]:
# Умножение матриц
np.dot(a, b)

array([[ 7,  0],
       [17, -2],
       [ 8, -3]])

In [54]:
# Транспонирование
a.T

array([[1, 3, 2],
       [2, 4, 1]])

Матричные операции, в основном, реализованы в модуле linalg пакета numpy.

In [55]:
from numpy import linalg as la

In [56]:
# Возведение в степень
la.matrix_power(b, 2)

array([[ 5, -8],
       [ 8, -3]])

In [57]:
# Определитель
la.det(b)

6.999999999999999

In [58]:
# Обратная матрица
c = la.inv(b)

In [59]:
np.dot(c, b)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [60]:
np.dot(b, c)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

## Контрольные вопросы

1. Может ли массив ndarray содержать данные различных типов?
1. Меняет ли метод reshape форму исходного массива?
1. Какой результат даст умножение (*) двумерного массива на число? На одномерный массив?
1. Дайте определение операции транспонирования двумерного массива (матрицы)
1. Как транспонировать одномерный массив?

## Задачи для самостоятельного выполнения:

**Макулатура**. Десять классов школы c 1 по 11, три месяца подряд собирали макулатуру, за каждый месяц известно количество килограмм собранных каждым классом. Три массива формы (10,1). 
1. Найти суммарное количество собранной школой макулатуры, количество собранной каждым классом макулатуры, среднее количество макулатуры за каждый месяц. 
2. Если известна стоимость одного кг., найти сумму заработка за каждый месяц; максимальную сумму набранную каким либо классом за один месяц; среднюю сумму по каждому классу. 
3. Найти количество классов, собравших макулатуры меньше среднего значения.
4. Найти величину наибольшего прогресса в последний месяц, по сравнению с предыдущим?

*указание* Три массива объединить в один, затем использовать операции библиотеки numpy.