<a href="https://colab.research.google.com/github/Alvald1/HSE_colab/blob/main/Final_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 0.1 Загрузите библиотеки

In [2]:
import numpy as np 
import sqlite3
import pandas as pd

#### 1.1 Как объединить два массива Numpy?

In [6]:
a=np.array([[1,2,3]])
b=np.array([[8,9,10]])

c = np.concatenate((a, b), axis=1)

c

array([[ 1,  2,  3,  8,  9, 10]])

#### 1.2 Напишите код на языке "Python" для получения индексов из 3 максимальных значений в массиве NumPy.
Пример:

Input: a = np.array([1, 3, 2, 4, 5])

Output: [4 3 1]

In [9]:
a = np.array([1, 3, 2, 4, 5])

print(np.argmax(a))

4


#### 1.3 Создайте массив размерностью "10x10" со случайными значениями и найдите минимум и максимум в этом массиве

In [11]:
data = np.random.randint(0, 100, (10, 10))
print(data)
print(np.max(data))
print(np.min(data))

[[62  7 78 92 64 74  7 22 16 60]
 [59 64 45 13 73 60 14 55 99 33]
 [11 56 81 14 61 35 33 55 74 75]
 [48 11 13 46 29 81 73  0 65 23]
 [42 73 49  5 67 41 97 55 52 30]
 [62 78 64 25 37 76 45 62 18 15]
 [84 96 20 16 98 54  7 28 73 82]
 [32  0 97 56 59 12  2 61 54  1]
 [68 14 99 52 44 28 38 66 24 66]
 [94  7 21 53 16 73 43 73 70 33]]
99
0


#### 1.4 Создать "8x8" матрицу и заполнить её в шахматном порядке
Подсказка: Можно сделать через функцию "tile"

In [13]:

np.fromfunction(lambda i,j: (i + j) % 2, (8, 8), dtype=int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 1.5 Отнять среднее из каждой строки в матрице состоящей из случайных чисел

In [16]:
data = np.random.randint(0, 100, (10, 10))
print(data)
tmp = np.average(data)
data=data-tmp
data

[[96  1 65 68 49 35 41 52 87  9]
 [15 94 44 82 89 13 28 64 48 67]
 [88 22 44 23 94 38 35 21 28 26]
 [62 64 68 35 55  3 92 71 39 12]
 [ 6 39 72 25 66 49 48 17 60 79]
 [ 6 93 26 43 32 36 31 84 40 77]
 [54 11 58 37 80  0 56 99 44 78]
 [10 95 48 82 11  9 90 75 95 14]
 [61 32 93 43 95  9  1 46 34 68]
 [48 23 70 20  9 33 29 62 56 12]]


array([[ 48.14, -46.86,  17.14,  20.14,   1.14, -12.86,  -6.86,   4.14,
         39.14, -38.86],
       [-32.86,  46.14,  -3.86,  34.14,  41.14, -34.86, -19.86,  16.14,
          0.14,  19.14],
       [ 40.14, -25.86,  -3.86, -24.86,  46.14,  -9.86, -12.86, -26.86,
        -19.86, -21.86],
       [ 14.14,  16.14,  20.14, -12.86,   7.14, -44.86,  44.14,  23.14,
         -8.86, -35.86],
       [-41.86,  -8.86,  24.14, -22.86,  18.14,   1.14,   0.14, -30.86,
         12.14,  31.14],
       [-41.86,  45.14, -21.86,  -4.86, -15.86, -11.86, -16.86,  36.14,
         -7.86,  29.14],
       [  6.14, -36.86,  10.14, -10.86,  32.14, -47.86,   8.14,  51.14,
         -3.86,  30.14],
       [-37.86,  47.14,   0.14,  34.14, -36.86, -38.86,  42.14,  27.14,
         47.14, -33.86],
       [ 13.14, -15.86,  45.14,  -4.86,  47.14, -38.86, -46.86,  -1.86,
        -13.86,  20.14],
       [  0.14, -24.86,  22.14, -27.86, -38.86, -14.86, -18.86,  14.14,
          8.14, -35.86]])

#### 1.6* Дан массив 16x16, посчитать сумму по блокам 4x4

In [21]:
data = np.random.randint(0, 10, (16, 15))
print(data)
print(data[:4,:4])

print(data[4:8,4:8])

[[5 0 7 2 8 4 2 7 6 3 8 2 0 0 5]
 [9 9 5 9 9 1 5 9 8 9 8 2 9 2 7]
 [5 7 3 1 6 1 0 8 7 5 9 8 8 1 2]
 [6 6 7 5 6 0 8 2 2 6 4 9 7 2 4]
 [0 9 1 9 2 0 6 9 3 5 8 9 8 1 0]
 [7 9 0 2 3 7 3 9 1 6 6 7 8 5 8]
 [0 6 4 1 2 4 2 3 4 6 8 5 8 6 7]
 [2 7 5 5 6 6 1 6 0 9 7 2 1 1 8]
 [9 4 4 0 2 5 7 7 2 8 1 4 6 2 9]
 [7 8 0 2 9 5 7 1 1 0 4 4 6 0 6]
 [5 2 1 6 7 1 8 6 9 4 7 3 0 0 3]
 [7 6 9 1 2 7 7 6 2 3 4 3 5 4 3]
 [6 3 1 5 2 3 5 1 6 0 6 8 8 8 4]
 [8 3 8 6 2 0 7 1 3 4 8 8 7 4 5]
 [5 7 4 8 5 9 9 8 1 9 5 3 2 1 4]
 [6 0 0 5 7 4 7 5 4 4 1 2 6 2 5]]
[[5 0 7 2]
 [9 9 5 9]
 [5 7 3 1]
 [6 6 7 5]]
[[2 0 6 9]
 [3 7 3 9]
 [2 4 2 3]
 [6 6 1 6]]


#### 2.1 Как создать Pandas series?

In [23]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'b', 'c'])
print(ser)

a    1
b    2
c    3
dtype: int64


#### 2.2 Как создать Pandas dataframe?

In [29]:
df = pd.read_excel('FT_1.xlsx')
df.head(3)

1      2      3      4      5
0      id  10001  10002  10003  10004
1   class      4      4      5      5
2  person    237    355    211    198

#### 2.3 Создайте датафрейм со следующими значениями столбцов:
"A": [420, 380, 390]
"B": [50, 40, 45]

Посчитайте столбец "C", в котором будет произведение поэлементно из "A" и "B":

"C": [21000,15200,17550]

In [36]:
A=np.array([420, 380, 390])
B=np.array([50, 40, 45])
d = {"A": A ,  "B": B, 'C': np.array([])}
ser = pd.Series(data=d, index=['A', 'B', 'C'])
ser['C']=ser['A']*ser['B']
print(ser)

A          [420, 380, 390]
B             [50, 40, 45]
C    [21000, 15200, 17550]
dtype: object


#### 2.4 Создайте датафрейм с 5 атрибутами, состоящими из рандомных чисел от 100 до 1000 и посчитайте сумму, максимальный и минимальный элементы по строкам и столбцам.

#### 2.5 У вас есть "строка" создать из нее датафрейм и разделить ее на два атрибута (столбца) - "code" и "location"  
{'row': ['00000 UNITED STATES', '01000 ALABAMA', 
                           '01001 Autauga County, AL', '01003 Baldwin County, AL', 
                           '01005 Barbour County, AL']}

##### Результат

#### 2.6 Опишите каждую строку в функции describe

#### 2.7* Опишите все виды соединений (слияний) в Pandas dataframe (и покажите каждый)**

#### 3.1 Создайте подключение к базе данных

In [40]:
conn = sqlite3.connect(':memory:') # или :memory: чтобы сохранить в RAM
cursor = conn.cursor()

#### 3.2 Создайте таблицу с id INTEGER PRIMARY KEY и 5 атрибутами(столбцами) в этой базе, заполните ее 5 строчками

In [46]:
cursor.execute("""CREATE TABLE IF NOT EXISTS tab
                  (id INTEGER PRIMARY KEY , a TEXT, b TEXT, c TEXT, d TEXT, e TEXT)
               """)

albums = [('Pink Floyd', 'The Wall', 'Columbia Records', '23', '197'),
          ('Pink Floyd', 'The Wall', 'Columbia Records', '23', '197'),
          ('Pink Floyd', 'The Wall', 'Columbia Records', '23', '197'),
          ('Pink Floyd', 'The Wall', 'Columbia Records', '23', '197'),
          ('Pink Floyd', 'The Wall', 'Columbia Records', '23', '197')]
cursor.executemany(
    "INSERT INTO tab(a, b, c, d, e) VALUES (?,?,?,?,?)", 
    albums
)
conn.commit()

#### 3.3 Обновите одну из ранее вставленных строчек 

In [48]:
cursor.execute("UPDATE tab SET a=? WHERE id=?",('1970', 3))

#### 3.4 Добавте эти же строчки через pandas dataframe

#### 3.5 Покажите возможности агрегирующих функций (2-3 любых запроса с ними)

---



In [55]:
cursor.execute("""CREATE TABLE IF NOT EXISTS tab2
                  (id INTEGER PRIMARY KEY , a integer, b integer, c integer, d integer, e integer)
               """)

a=[(324,124,674,124,65),
   (324,124,300,124,65),
   (324,124,2,124,65),
   (324,124,674,124,65),
   (324,124,1,124,65)]

cursor.executemany(
    "INSERT INTO tab2(a, b, c, d, e) VALUES (?,?,?,?,?)", 
    a
)
conn.commit()

cursor.execute("""
SELECT max(c) FROM tab2 
WHERE c<=200""" )

SQLres=cursor.fetchone()
print(SQLres)

cursor.execute("""
SELECT min(c) FROM tab2 """ )

SQLres=cursor.fetchone()
print(SQLres)

cursor.execute("""
SELECT sum(c) FROM tab2 """ )

SQLres=cursor.fetchone()
print(SQLres)

(2,)
(0,)
(11476,)


#### 3.6 Продемонстрируйте возможности оператора case-when-then

In [57]:
cursor.execute("""SELECT a, b,
CASE
    WHEN c > 30 THEN 'The quantity is greater than 30'
    WHEN c = 30 THEN 'The quantity is 30'
    ELSE 'The quantity is under 30'
FROM tab2""")

SQLres=cursor.fetchall()
print(SQLres)

OperationalError: ignored

#### 3.7* Транспонируйте таблицу по атрибутам

In [ ]:
df = pd.read_excel('FT_1.xlsx')
df

1            2            3            4            5
0      id        10001        10002        10003        10004
1   class            4            4            5            5
2  person          237          355          211          198
3  gender          "M"          "Ж"          "Ж"          "М"
4  number  79602336578  79602336578  79802931277  79802931277

In [ ]:
#Должно получиться вот так

id  class  person gender       number
0  10001      4     237      М  79602336578
1  10002      4     355      Ж  79602336578
2  10003      5     211      Ж  79802931277
3  10004      5     198      М  79802931277